version: '3.1'
services:
  fire-spread-database:
      container_name: fire-spread-database
      image: postgres:alpine
      restart: always
      environment:
        POSTGRES_PASSWORD: password
        POSTGRES_USER: user
        POSTGRES_DB: database
      ports:
        - 5432:5432
      volumes:
        - ./.docker/database:/var/lib/postgresql/data